interface IDemo {
  'KUBEFLOW_HOST': string;
  'CODE_MANAGER_URL': string;
  'NOTEBOOK_COMPONENT_CATALOG_GIT_REPO': string;
  'CONTINUOUS_DELIVERY_INTEGRATION_URL': string;
  'ONNX_GENERATOR_FRAME_URL': string;
  'ONNX_GENERATOR_REQUEST_URL': string;
  'KUBEFLOW_AUTO_LOGIN_PAGE': string;
  'NOTEBOOK_RUNTIMES': string;
  'GPU_VENDORS': string;
  'CLUSTER_MANAGER_URL': string;
  'DOCUMENT_MANAGER_URL': string;
  'NOTEBOOK_DEFAULT_ENVIRONMENTS': string;
  'CLUSTER_ID': string;
}