export const EVENT_TYPE = {
  CONTOLER_CLICK: 'TIME_CONTROLLER_CLICK', // 时间条点击，切换当前播放进度

  AI_BAR_CLICK: 'TIME_CONTROLLER_AI_BAR_CLICK', // AI条点击，切换当前播放进度

  START_DRAG: 'TIME_CONTROLLER_START_DRAG', // 开始拖拽事件

  DRAGING: 'TIME_CONTROLLER_DRAGING', // 拖动中

  STOP_DRAG: 'TIME_CONTROLLER_STOP_DRAG', // 结束拖拽事件

  SCROLL: 'TIME_CONTROLLER_SCROLL', // 滚动事件

  ZOOM: 'TIME_CONTROLLER_ZOOM', // 颗粒度切换

  STEP: 'TIME_CONTROLLER_STEP', // 当前刻度自动前进
}
