image: node:16.14.2

stages:
  - install
  - build
  - release

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - node_modules/

install:
    stage: install
    script:
      - pwd
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm update

dev-build:
  stage: build
  script:
    - npm run pre
  artifacts:
    name: "dist"
    paths:
      - dist
    expire_in: 1 day
  except:
    - /^release\/.*$/
    - master

dev-docker:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  script:
    - tag=$(date +%Y%m%d%H%M%S)_${CI_COMMIT_SHA:0:6}
    - docker build -t ${CI_REGISTRY_IMAGE}:${tag} .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}:${tag}
  when: manual
  except:
    - /^release\/.*$/
    - master

release-build:
  stage: build
  script:
    - npm run release
  artifacts:
    name: "dist"
    paths:
      - dist
    expire_in: 1 week
  only:
    - /^release\/.*$/
    - master

release-docker:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  script:
    - tag=$(date +%Y%m%d%H%M%S)_${CI_COMMIT_SHA:0:6}
    - docker build -t ${CI_REGISTRY_IMAGE}:${tag} .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}:${tag}
  only:
    - /^release\/.*$/
    - master
  when: manual

